import { cors, getText, clean, extractPlace } from './_lib.js';

function decode(s=''){return s.replace(/\\u002F/g,'/').replace(/\\u0026/g,'&').replace(/&amp;/g,'&')}
function pickAddress(block=''){const patterns=[/"roadAddress"\s*:\s*"([^"]+)"/i,/"address"\s*:\s*"([^"]+)"/i,/"fullAddress"\s*:\s*"([^"]+)"/i];for(const p of patterns){const m=block.match(p);if(m)return clean(decode(m[1]))}return ''}
function pickName(block='',brand=''){const patterns=[/"name"\s*:\s*"([^"]+)"/i,/"businessName"\s*:\s*"([^"]+)"/i,/"display"\s*:\s*"([^"]+)"/i];for(const p of patterns){const m=block.match(p);if(m&&m[1].includes(brand))return clean(decode(m[1]))}return brand}
function parseMap(html,brand){const text=decode(html);const out=[],seen=new Set();const re=/(?:placeId|entryId|id)\\?"?\s*[:=]\s*\\?"?([0-9]{5,})/gi;let m;while((m=re.exec(text))){const id=m[1];if(seen.has(id))continue;const block=text.slice(Math.max(0,m.index-1200),Math.min(text.length,m.index+2200));if(!block.includes(brand))continue;seen.add(id);out.push({name:pickName(block,brand),address:pickAddress(block),place_id:id,map_url:`https://map.naver.com/p/entry/place/${id}`});if(out.length>=100)break}return out}
async function searchOne(brand){const q=encodeURIComponent(brand);const urls=[`https://map.naver.com/p/search/${q}`,`https://map.naver.com/v5/search/${q}`];for(const url of urls){try{const html=await getText(url,{headers:{referer:'https://map.naver.com/'}});const rows=parseMap(html,brand);if(rows.length)return{rows,source:url}}catch{}}
return{rows:[],source:null}}
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='GET')return res.status(405).json({ok:false,error:'GET only'});try{const brand=clean(req.query.brand||'');if(brand.length<2)return res.status(400).json({ok:false,error:'브랜드명을 2글자 이상 입력하세요'});const {rows,source}=await searchOne(brand);if(!rows.length){const q=encodeURIComponent(brand);const html=await getText(`https://search.naver.com/search.naver?query=${q}`);const p=extractPlace(html);if(p)return res.status(200).json({ok:true,brand,count:1,stores:[{name:brand,address:'',place_id:p.id,map_url:`https://map.naver.com/p/entry/place/${p.id}`}],source:'naver-search-fallback',notice:'네이버 지도 검색에서 전체 목록을 추출하지 못해 대표 플레이스만 반환했습니다.'});throw new Error('네이버 지도에서 해당 브랜드 매장을 찾지 못했습니다');}return res.status(200).json({ok:true,brand,count:rows.length,stores:rows,source:'naver-map',source_url:source});}catch(e){return res.status(502).json({ok:false,error:String(e.message||e)});}}
